export const AppConfig = {
    SECRET_KEY: "Diozsepth160QQWmLnNuOnnF13iorma",
    EXPIRATION_TOKEN: "1h",
    EXPIRATION_SESSION_IN_DB: 3600,
    EXPIRATION_TEMPORAL_TOKEN: "30m",
    EXPIRATION_TEMPORAL_TOKEN_IN_DB: 60 * 30,
    TIME_IN_CACHE: 100
}